kind: Pod
apiVersion: v1
metadata:
  name: secrets-test-pod
spec:
  containers:
    - name: test-container
      image: nginx
      volumeMounts:
      - name: secrets-store01-inline
        mountPath: "/mnt/secrets"
        readOnly: true
  volumes:
    - name: secrets-store01-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "azure-kv-provider" # Links to your YAML from Phase 3